# Generated by Django 4.2 on 2023-09-29 01:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hives", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Hives",
            new_name="Hive",
        ),
    ]
