# Generated by Django 4.2 on 2023-11-17 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("hives", "0004_remove_hive_description_hive_comments_collection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="hive",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="hives.hive",
            ),
        ),
    ]
