# Generated by Django 4.2 on 2023-11-17 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("hives", "0005_alter_collection_hive"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="hive",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="hives.hive"
            ),
        ),
    ]
