# Generated by Django 4.2 on 2023-11-18 02:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hives", "0007_hivesnapshot"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hive",
            name="responsible",
        ),
        migrations.AddField(
            model_name="hive",
            name="q_ca",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Quantidade de quadros com alimento"
            ),
        ),
        migrations.AddField(
            model_name="hive",
            name="q_cf",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Quantidade de quadros com cria"
            ),
        ),
        migrations.AddField(
            model_name="hive",
            name="q_ci",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Quantidade de quadros com insetos"
            ),
        ),
        migrations.AddField(
            model_name="hive",
            name="q_cv",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Quantidade de quadros com vazio"
            ),
        ),
        migrations.AddField(
            model_name="hive",
            name="q_total",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Quantidade de quadros totais"
            ),
        ),
        migrations.AddField(
            model_name="hive",
            name="queen_status",
            field=models.CharField(
                choices=[
                    ("REGULAR", "REGULAR"),
                    ("DEVELOPMENT", "DEVELOPMENT"),
                    ("WEAK", "WEAK"),
                ],
                default="REGULAR",
                max_length=30,
                verbose_name="Status da Rainha",
            ),
        ),
        migrations.AlterField(
            model_name="hive",
            name="status",
            field=models.CharField(
                choices=[
                    ("CAPTURE", "Capture"),
                    ("DEVELOPMENT", "Development"),
                    ("PRODUCTIVE", "Productive"),
                    ("EMPTY_BOX", "Empty Box"),
                ],
                default="CAPTURE",
                max_length=30,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="hivesnapshot",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CAPTURE", "Capture"),
                    ("DEVELOPMENT", "Development"),
                    ("PRODUCTIVE", "Productive"),
                    ("EMPTY_BOX", "Empty Box"),
                ],
                max_length=30,
                null=True,
                verbose_name="Status",
            ),
        ),
    ]
