# Generated by Django 4.2 on 2023-11-20 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0002_remove_user_office_remove_user_sector"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Administrador"),
                    ("SUPPORT", "Suporte"),
                    ("MEMBER", "Membro"),
                ],
                default="MEMBER",
                max_length=30,
            ),
        ),
    ]
